CREATE DATABASE IF NOT EXISTS taken_db;
USE taken_db;

CREATE TABLE IF NOT EXISTS taaks (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    naam VARCHAR(255) NOT NULL,
    voltooid TINYINT(1) DEFAULT 0,
    created_at TIMESTAMP NULL DEFAULT NULL,
    updated_at TIMESTAMP NULL DEFAULT NULL
);